[package]
name = "cronrunner"
version = "2.17.0"
edition = "2024"
authors = ["Quentin Richert <noreply@richert.co>"]
description = "Run cron jobs manually."
license = "MIT OR Apache-2.0"
repository = "https://github.com/qrichert/cronrunner.git"
readme = "README.md"
keywords = ["cron", "crontab", "cron-jobs", "job-runner", "automation"]
categories = ["command-line-utilities"]

[[bin]]
name = "crn"
path = "src/main.rs"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
strip = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }

[dependencies]
# Output text through a pager.
lessify = "0.6.0"
